version: '3'
services:
    db:
        image: postgres
        container_name: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: admin
        ports:
            - '5432:5432'
        volumes:
            - "$PWD":/var/lib/postgresql/data
        networks:
            -   postgres
    admin:
        image: fenglc/pgadmin4
        container_name: pgadmin4
        restart: always
        ports:
            - '5050:5050'
        networks:
            -   postgres
networks:
    postgres:
        driver: bridge
